version: "3.2"
services:
  dgraph-zero:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080

  dgraph-server:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=server:7080 --lru_mb=2048 --zero=zero:5080

  dgraph-ratel:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
    command: dgraph-ratel

  api:
    image: wikidist-api
    build:
      context: .
      dockerfile: docker/api.Dockerfile

  frontend:
    image: wikidist-frontend
    build:
      context: .
      dockerfile: docker/front.Dockerfile
    ports:
      - 8085:8080

volumes:
  dgraph:
